#!/bin/bash
var1=10
var2=20

if [ $var1 -gt 5 ]
then 
   echo "THe test value $var1 is greater than 5"
fi

if [ $var1 -eq $var2 ]
then echo "The values are equal"
else
echo "The values are different"
fi 
